apiVersion: v1
kind: Service
metadata:
  name: flask-api-service-v1
  namespace: v1
spec:
  type: ClusterIP
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
